name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-deploy-main:
    runs-on: ubuntu-latest
    environment: deeptrack-travel-backend
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        # Push the image to Docker Hub
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/deepstack-travel-backend:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_EC2_USER }}
        key: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }}
        script_stop: true # Stop script execution if any command fails
        source: "docker-compose.yml"
        target: "/home/${{ secrets.AWS_EC2_USER }}/deepstack-travel-backend"
        script: |
          # Ensure the deployment directory exists
          mkdir -p /home/${{ secrets.AWS_EC2_USER }}/deepstack-travel-backend
          cd /home/${{ secrets.AWS_EC2_USER }}/deepstack-travel-backend
          
          # Create .env file from secrets
          echo "DB_URL=${{ secrets.DB_URL }}" > .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DOCKERHUB_USERNAME"=${{ secrets.DOCKERHUB_USERNAME }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "JWT_EXPIRATION_SECONDS=${{ secrets.JWT_EXPIRATION_SECONDS }}" >> .env
          
          # Pull latest images
          docker-compose pull
          
          # Stop and restart services
          docker-compose up -d --force-recreate
          
          # Remove unused images
          docker image prune -f
